# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-10 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeground', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='selling',
        ),
    ]
