# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-10 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeground', '0003_business_selling'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
