# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-10 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeground', '0004_business_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
