# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeground', '0006_comment_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
