# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeground', '0007_business_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='poster',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
