# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-15 05:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeground', '0008_business_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='business',
        ),
    ]
