# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-16 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeground', '0009_remove_comment_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='business',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='homeground.Business'),
        ),
    ]
